site_name: Awesome BUPT SCS
docs_dir: projects
nav:
  - 首页:
    - 项目介绍: index.md
  - 课程列表:
    - 计算导论与程序设计课程设计: Introduction-to-Computing-and-Foundation-of-Programming.md
    - 数据结构: Data-Structures.md
    - 数据结构课程设计: Project-Laboratory-Algorithms-and-Data-Structures.md
    - 计算机网络: Computer-Networks.md
    - 计算机网络课程设计: Advanced-Labs-in-Computer-Networks.md
    - 计算机组成原理课程设计: Advanced-Labs-in-Computer-Architecture.md
    - 面向对象程序设计实践 (C++): C++.md
    - 编译原理与技术: Compilers.md
    - 操作系统: Operating-Systems.md
    - 操作系统课程设计: Advanced-Labs-in-Operating-Systems.md
    - 程序设计实践: Program-Practice.md
    - 数据库系统原理: Database.md
    - 数据库系统原理课程设计: Advanced-Labs-in-Database.md
    - 软件工程: Software-Engineering.md
    - 计算机系统结构: Computer-Architecture.md
    - 现代交换原理: Switcher.md
    - 网络技术实践: Network-Practice.md
    - 信息与知识获取: Info-Know.md
    - Linux 开发环境及应用: Linux.md
    - 移动互联网技术及应用: Mobile-Internet-Technology-and-Application.md
    - 自然语言处理: NLP.md
repo_url: https://github.com/brupst/awesome-bupt-scs
repo_name: brupst/awesome-bupt-scs
theme:
  name: material
  language: zh
  features:
    - tabs